routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('users', UserController::class);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * Get the items for the category.
     */
    public function items()
    {
        return $this->hasMany(Item::class);
    }
}

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Item extends Model
{
    use HasFactory, SoftDeletes;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * Get the category that owns the item .
     */
    public function category()
    {
        return $this->belongsTo(Category::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Hash;

class User extends Authenticatable
{
    use HasFactory, Notifiable, SoftDeletes;

    protected $perPage = 20;

    /**
     * The attributes that aren't mass assignable.
     *
     * @var array
     */
    protected $guarded = [];

    /**
     * Store info users to database
     * 
     * @param object $request 
     */
    public function createUser($request)
    {
        $input = $request->except('password_confirmation');
        $input['password'] = Hash::make($input['password']);
        User::create($input);
    }

    /**
     * Get list users
     * 
     * @return Illuminate\Pagination\Paginator
     */
    public function getUsers()
    {
        return User::orderBy('mail_address')->paginate();
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Models\User;
use App\Http\Requests\CreateUserRequest;

class UserController extends Controller
{
    protected $userModel;

    public function __construct(User $user)
    {
        $this->userModel = $user;
    }
    /**
     * Show list users
     * 
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $notify = session()->get('status') ?? '';
        return view('users.list', [
            'notify' => $notify,
            'users'  => $this->userModel->getUsers()
        ]);
    }

    /**
     * Show the form to create a user
     * 
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.create');
    }

    /**
     * Store a new user
     *
     * @param  \App\Http\Requests\CreateUserRequest  $request
     * @return  \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $this->userModel->createUser($request);
        session()->flash('status', 'Thêm người dùng thành công');
        return redirect()->route('users.index');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @yield('title')
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    @stack('style')
</head>
<body>
    <header>
        @include('partitions.header')
    </header>
    <main>
        <div class="main__content" style="margin:60px 0;">
            @yield('content')
        </div>
    </main>
    <footer class="text-center text-lg-start bg-light text-muted">
        @include('partitions.footer')
    </footer>
</body>
</html>

resources/views/partitions/footer.blade.php
<section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    <!-- Left -->
    <div class="me-5 d-none d-lg-block">
            <span>Get connected with us on social networks:</span>
    </div>
    <!-- Left -->

    <!-- Right -->
    <div>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-facebook-f"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-twitter"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-google"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-instagram"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-linkedin"></i>
            </a>
            <a href="" class="me-4 text-reset">
                <i class="fab fa-github"></i>
            </a>
    </div>
    <!-- Right -->
</section>
<!-- Section: Social media -->

<!-- Section: Links  -->
<section class="">
    <div class="container text-center text-md-start mt-5">
    <!-- Grid row -->
        <div class="row mt-3">
            <!-- Grid column -->
            <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
                <!-- Content -->
                <h6 class="text-uppercase fw-bold mb-4">
                    <i class="fas fa-gem me-3"></i>MONSTARLAB
                </h6>
                <p>
                    Here you can use rows and columns to organize your footer content. Lorem ipsum
                    dolor sit amet, consectetur adipisicing elit.
                </p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                    Products
                </h6>
                <p>
                    <a href="#!" class="text-reset">Angular</a>
                </p>
                <p>
                    <a href="#!" class="text-reset">React</a>
                </p>
                <p>
                    <a href="#!" class="text-reset">Vue</a>
                </p>
                <p>
                    <a href="#!" class="text-reset">Laravel</a>
                </p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                    Useful links
                </h6>
                <p>
                    <a href="#!" class="text-reset">Pricing</a>
                </p>
                <p>
                    <a href="#!" class="text-reset">Settings</a>
                </p>
                <p>
                    <a href="#!" class="text-reset">Orders</a>
                </p>
                <p>
                    <a href="#!" class="text-reset">Help</a>
                </p>
            </div>
            <!-- Grid column -->

            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
                <!-- Links -->
                <h6 class="text-uppercase fw-bold mb-4">
                    Contact
                </h6>
                <p>
                    <i class="fas fa-home me-3"></i> New York, NY 10012, US</p>
                <p>
                    <i class="fas fa-envelope me-3"></i>info@example.com
                </p>
                <p><i class="fas fa-phone me-3"></i> + 01 234 567 88</p>
                <p><i class="fas fa-print me-3"></i> + 01 234 567 89</p>
            </div>
            <!-- Grid column -->
        </div>
        <!-- Grid row -->
    </div>
</section>
<!-- Section: Links  -->

<!-- Copyright -->
<div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright:
    <a class="text-reset fw-bold" href="https://mdbootstrap.com/">MDBootstrap.com</a>
</div>

resources/views/partitions/header.blade.php
<div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none" style="font-size: 25px;">
            MONSTARLAB
        </a>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="#" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Features</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">Pricing</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">FAQs</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">About</a></li>
        </ul>

        <div class="col-md-3 text-end">
        <button type="button" class="btn btn-outline-primary me-2">Login</button>
        <button type="button" class="btn btn-primary">Sign-up</button>
        </div>
    </header>
</div>

resources/views/users/create.blade.php
@extends('layouts.app')

@push('style')
	<style>
		.check{
			border: 1px solid red;
		}
		.message{
			color: red;
		}

		.form-group{
			margin-bottom: 20px
		}
	</style>
@endpush

@section('content')
<div class="container">
	<h3 style="margin-bottom:15px;">Thêm Người dùng</h3>
	<div class="row">
	  <div class="col-md-12">
		<form action="{{ route('users.store') }}" method="post">
		  @csrf            
		  <div class="form-group">
			  <label @error('name') class="message" @enderror>Name</label>
			  <input type="text" class="form-control @error('name') check @enderror" name="name"  value="{{ old('name') }}">
			  @error('name')
				  <span class="message">{{ $message }}</span>
			  @enderror
		  </div>
		  <div class="form-group">
			  <label @error('mail_address') class="message" @enderror>mail_address</label>
			  <input type="text" class="form-control @error('mail_address') check @enderror" name="mail_address"  value="{{ old('mail_address') }}">
			  @error('mail_address')
				  <span class="message">{{ $message }}</span>
			  @enderror
		  </div>
		  <div class="form-group">
			  <label @error('password') class="message" @enderror>password</label>
			  <input type="password" class="form-control @error('password') check @enderror" name="password">
			  @error('password')
				  <span class="message">{{ $message }}</span>
			  @enderror
		  </div>
		  <div class="form-group">
			  <label @error('password_confirmation') class="message" @enderror>password_confirmation</label>
			  <input type="password" class="form-control @error('password_confirmation') check @enderror" name="password_confirmation">
			  @error('password_confirmation')
				  <span class="message">{{ $message }}</span>
			  @enderror
		  </div>
		  <div class="form-group">
			  <label @error('address') class="message" @enderror>address</label>
			  <input type="text" class="form-control @error('address') check @enderror" name="address"  value="{{ old('address') }}">
			  @error('address')
				  <span class="message">{{ $message }}</span>
			  @enderror
		  </div>
		  <div class="form-group">
			  <label @error('phone') class="message" @enderror>phone</label>
			  <input type="text" class="form-control @error('phone') check @enderror" name="phone"  value="{{ old('phone') }}">
			  @error('phone')
				  <span class="message">{{ $message }}</span>
			  @enderror
		  </div>
		  <button type="submit" class="btn btn-primary">Thêm mới</button>
		</form>
	  </div>
	</div>
  </div>
@endsection

resources/views/users/list.blade.php
@extends('layouts.app')

@section('content')
<h1>{{ $notify }}</h1>
<div class="container" style="margin-top:60px;">
    <a class="btn btn-primary" href="{{ route('users.create') }}" role="button" style="margin-bottom:15px;">Thêm mới</a>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-bordered">
                <thead>
                  <tr>
                    <th scope="col" class="text-center">STT</th>
                    <th scope="col" class="text-center">Địa chỉ email</th>
                    <th scope="col" class="text-center">Tên</th>
                    <th scope="col" class="text-center">Địa chỉ</th>
                    <th scope="col" class="text-center">Số điện thoại</th>
                  </tr>
                </thead>
                <tbody>
                    @php
                        $serial = ($users->currentPage() - 1) * $users->perPage();
                    @endphp                      
                    @foreach ($users as $user)
                        <tr>
                            <th scope="row">{{ ++$serial }}</th>
                            <td>{{ $user->mail_address }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->address }}</td>
                            <td>{{ $user->phone }}</td>
                        </tr>
                    @endforeach    
                </tbody>
              </table>
              <div>
                {{ $users->links() }}
              </div>
        </div>
    </div>
</div>
@endsection